# Generated by Django 5.1.4 on 2024-12-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0003_registrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='student_id',
            new_name='studentId',
        ),
    ]
