# Generated by Django 5.1.4 on 2024-12-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0004_rename_student_id_registrations_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
