# Generated by Django 5.1.4 on 2024-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0005_registrations_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
